### ISSUE TITLE
iOS9.3.5，开启astnc后，label不能换行

### ISSUE THREAD

**Issue by YGAS** [12207480/TYText#2]
iOS9.3.5，开启async后，label不能换行
![image](https://user-images.githubusercontent.com/1214708/43393526-181f3e0a-942a-11e8-82bc-0eacd364c86a.png)

**Comment by 12207480** [comment]
cell高度写死了 把行高写大点就可以了

**Comment by YGAS** [comment]
ok,确实跟高度有关系
