### ISSUE TITLE
使用TYTextView布局遇到一个问题

### ISSUE THREAD

**Issue by 624990742** [12207480/TYText#5]
<img width="453" alt="4a099346287973a0cabdf6e00fe77870" src="https://user-images.githubusercontent.com/18068125/48405985-5bf4f880-e76e-11e8-8220-0c4c95ac944b.png">
你好，我在使用TYTextView的时候遇到横线混乱的问题，希望能够得到你的帮助

**Comment by 12207480** [comment]
是否可以提供demo

**Comment by 624990742** [comment]
现在你提供的那个填空题的demo也存在这样的问题

**Comment by 12207480** [comment]
怎么复现？

**Comment by devtofu** [comment]
跟我提的 issues 是一样的 ，我试一下，如果解决了，就解决了内存的大问题

**Comment by 12207480** [comment]
解决了吗

**Comment by devtofu** [comment]
这个问题解决了 @12207480 我在我的 issuse 中提到了另外一个问题，麻烦大佬验证一下！
